"""mensaje de migración2 

Revision ID: 08df9cf8e523
Revises: 5555a4a522a1
Create Date: 2023-06-09 19:44:11.465446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08df9cf8e523'
down_revision = '5555a4a522a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_multi_file', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'archivos', ['file_id'], ['file_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_multi_file')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
