"""mensaje de migración3 

Revision ID: 42575ad75094
Revises: 08df9cf8e523
Create Date: 2023-06-11 20:41:59.666158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42575ad75094'
down_revision = '08df9cf8e523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.drop_constraint('archivos_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint('proyectos_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint('tests_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('tests_ibfk_2', type_='foreignkey')

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint('tokens_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_foreign_key('tokens_ibfk_1', 'usuarios', ['user_id'], ['user_id'])

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_foreign_key('tests_ibfk_2', 'archivos', ['file_id'], ['file_id'])
        batch_op.create_foreign_key('tests_ibfk_1', 'proyectos', ['proyecto_id'], ['project_id'])

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.create_foreign_key('proyectos_ibfk_1', 'usuarios', ['user_id'], ['user_id'])

    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.create_foreign_key('archivos_ibfk_1', 'proyectos', ['project_id'], ['project_id'])

    # ### end Alembic commands ###
