"""empty message

Revision ID: 5555a4a522a1
Revises: 
Create Date: 2023-05-31 15:21:15.427838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5555a4a522a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyecto_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('tests_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_id'], ['project_id'])
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tests_ibfk_1', 'archivos', ['file_id'], ['file_id'])
        batch_op.drop_column('proyecto_id')

    # ### end Alembic commands ###
