"""mensaje de migración5 

Revision ID: 8617a38d4b45
Revises: 42575ad75094
Create Date: 2023-06-14 02:01:21.656335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8617a38d4b45'
down_revision = '42575ad75094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('names_files', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('names_files')

    # ### end Alembic commands ###
